//! CSV output formatter for Spanish tax statements.
//!
//! Format per `specs/002-spain-tax/contracts/csv-output.md`. Unlike the German statement no row
//! carries a tax figure: the savings scale is progressive and applies to the year's whole base
//! after group compensation, so a per-row tax would be arithmetic nobody could add up.

use std::io::Write;

use crate::core::GenericResult;
use crate::taxes::spain::SpanishTaxRegime;
use crate::types::Decimal;

use super::statement::{
    CapitalGainEntry, DividendEntry, FeeEntry, FxGainEntry, InterestEntry, SpanishLotDetail,
    SpanishTaxStatement, WashSaleReintegrationEntry,
};

/// Modelo 109 box numbers.
///
/// Gipuzkoa publishes no static numbered form — the return is generated by the Zergabidea platform
/// — and the only official box map reachable is explicitly dated AÑO 2019.
// TODO(verify): every casilla below comes from the AÑO 2019 map
// (`egoitza.gipuzkoa.eus/documents/39465/25500467/5.FE-Errenta_maila_PFEZ-es.pdf`). The 2026 reform
// added a cuota-íntegra column to art. 76.1 and Anexo 3 gained a crypto section, either of which
// plausibly renumbered boxes. The casilla for the deducción por doble imposición internacional is
// not published anywhere reachable, for any year.
mod modelo_109 {
    pub const RCM_GROSS: &str = "06+16";
    pub const RCM_EXPENSES: &str = "17";
    pub const RCM_WITHHOLDING: &str = "07+22";
    pub const CAPITAL_GAINS: &str = "28";
    pub const SAVINGS_BASE: &str = "33";
    pub const NET_QUOTA: &str = "64";
}

/// CSV formatter for Spanish tax statements.
pub struct CsvFormatter;

impl CsvFormatter {
    /// Write the complete tax statement to CSV.
    pub fn write<W: Write>(statement: &SpanishTaxStatement, writer: &mut W) -> GenericResult<()> {
        Self::write_header(writer)?;

        for entry in &statement.capital_gains {
            Self::write_capital_gain_row(writer, entry)?;
            // Inline rather than in a separate section: the actualization arithmetic has to be
            // readable line by line directly under the sale it justifies.
            for lot in &entry.lots {
                Self::write_lot_row(writer, entry, lot)?;
            }
        }

        for entry in &statement.wash_sale_reintegrations {
            Self::write_reintegration_row(writer, entry)?;
        }

        for entry in &statement.dividends {
            Self::write_dividend_row(writer, entry)?;
        }

        for entry in &statement.interest {
            Self::write_interest_row(writer, entry)?;
        }

        for entry in &statement.fx_gains {
            Self::write_fx_gain_row(writer, entry)?;
        }

        for entry in &statement.fx_borrowed_review {
            Self::write_fx_borrowed_row(writer, entry)?;
        }

        for entry in &statement.fees {
            Self::write_fee_row(writer, entry)?;
        }

        Self::write_summary_rows(writer, statement)?;
        Self::write_carryforward(writer, statement)?;
        Self::write_deferred_losses(writer, statement)?;
        Self::write_modelo_boxes(writer, statement)?;
        Self::write_warnings(writer, statement)?;

        Ok(())
    }

    fn write_header<W: Write>(writer: &mut W) -> GenericResult<()> {
        writeln!(
            writer,
            "transaction_type,transaction_date,settle_date,symbol,isin,description,quantity,cost_eur,coefficient,actualized_cost_eur,proceeds_eur,gross_amount_eur,gain_loss_eur,deferred_loss_eur,integrable_amount_eur,foreign_tax_eur,treaty_capped_credit_eur,savings_group,notes"
        )?;
        Ok(())
    }

    fn write_capital_gain_row<W: Write>(
        writer: &mut W,
        entry: &CapitalGainEntry,
    ) -> GenericResult<()> {
        // The coefficient cell is empty here on purpose: it is a per-lot figure, and one sale can
        // consume lots of several vintages. The `Lot` rows below carry it.
        writeln!(
            writer,
            "Capital Gain,{},{},{},{},{},{},{},,{},{},,{},{},{},,,GyP,{}",
            Self::format_date(entry.sale_date),
            Self::format_date(entry.settle_date),
            Self::escape_csv(&entry.symbol),
            Self::escape_csv(&entry.isin),
            Self::escape_csv(&entry.description),
            Self::format_decimal(entry.quantity),
            Self::format_decimal(entry.cost_eur),
            Self::format_decimal(entry.actualized_cost_eur),
            Self::format_decimal(entry.proceeds_eur),
            Self::format_decimal(entry.fiscal_gain_loss),
            Self::format_decimal(entry.deferred_loss),
            Self::format_decimal(entry.integrable_amount),
            Self::escape_csv(entry.notes.as_deref().unwrap_or(""))
        )?;
        Ok(())
    }

    fn write_lot_row<W: Write>(
        writer: &mut W,
        sale: &CapitalGainEntry,
        lot: &SpanishLotDetail,
    ) -> GenericResult<()> {
        // The note spells the multiplication out so an auditor can check the actualized cost
        // without re-deriving which coefficient applied to which vintage.
        let arithmetic = format!(
            "{} × {} = {}",
            Self::format_decimal(lot.cost_eur),
            Self::format_coefficient(lot.coefficient),
            Self::format_decimal(lot.actualized_cost_eur)
        );

        writeln!(
            writer,
            "Lot,{},,{},,{},{},{},{},{},{},,{},,,,,GyP,{}",
            Self::format_date(lot.acquisition_date),
            Self::escape_csv(&sale.symbol),
            Self::escape_csv(&format!(
                "FIFO lot acquired {}",
                Self::format_date(lot.acquisition_date)
            )),
            Self::format_decimal(lot.quantity),
            Self::format_decimal(lot.cost_eur),
            Self::format_coefficient(lot.coefficient),
            Self::format_decimal(lot.actualized_cost_eur),
            Self::format_decimal(lot.proceeds_eur),
            Self::format_decimal(lot.gain_eur),
            Self::escape_csv(&arithmetic)
        )?;
        Ok(())
    }

    fn write_reintegration_row<W: Write>(
        writer: &mut W,
        entry: &WashSaleReintegrationEntry,
    ) -> GenericResult<()> {
        // Negative amounts: a released deferral is a loss becoming deductible, so it reduces the
        // ganancias group in the year the blocking shares left the estate.
        let released = -entry.released_eur;
        writeln!(
            writer,
            "Wash Sale Reintegration,{},,{},{},{},,,,,,,{},,{},,,GyP,{}",
            Self::format_date(entry.date),
            Self::escape_csv(&entry.symbol),
            Self::escape_csv(&entry.isin),
            Self::escape_csv(&format!(
                "Deferred loss released by the disposal of shares acquired {}",
                Self::format_date(entry.acquisition_date)
            )),
            Self::format_decimal(released),
            Self::format_decimal(released),
            Self::escape_csv(&format!(
                "Deferred by the sale of {} (NF 3/2014 art. 43 closing ¶ / LIRPF art. 33.5 closing ¶)",
                Self::format_date(entry.origin_sale_date)
            ))
        )?;
        Ok(())
    }

    fn write_dividend_row<W: Write>(writer: &mut W, entry: &DividendEntry) -> GenericResult<()> {
        // Dividend records carry no share quantity; leave that cell empty rather than a misleading 0.
        writeln!(
            writer,
            "Dividend,{},{},{},{},{},,,,,,{},,,,{},{},RCM,",
            Self::format_date(entry.date),
            Self::format_date(entry.date),
            Self::escape_csv(&entry.symbol),
            Self::escape_csv(&entry.isin),
            Self::escape_csv(&entry.description),
            Self::format_decimal(entry.gross_eur),
            Self::format_decimal(entry.withheld_eur),
            Self::format_decimal(entry.treaty_capped_credit)
        )?;
        Ok(())
    }

    fn write_interest_row<W: Write>(writer: &mut W, entry: &InterestEntry) -> GenericResult<()> {
        writeln!(
            writer,
            "Interest,{},{},CASH,,{},,,,,,{},,,,,,RCM,",
            Self::format_date(entry.date),
            Self::format_date(entry.date),
            Self::escape_csv(&entry.description),
            Self::format_decimal(entry.gross_eur)
        )?;
        Ok(())
    }

    fn write_fx_gain_row<W: Write>(writer: &mut W, entry: &FxGainEntry) -> GenericResult<()> {
        let description = format!(
            "{} balance acquired {} ({})",
            entry.currency,
            Self::format_date(entry.acquisition_date),
            entry.activity_code
        );
        writeln!(
            writer,
            "FX Gain/Loss,{},,{},,{},,,,,,,{},,{},,,GyP,",
            Self::format_date(entry.date),
            Self::escape_csv(&entry.currency),
            Self::escape_csv(&description),
            Self::format_decimal(entry.amount_eur),
            Self::format_decimal(entry.amount_eur)
        )?;
        Ok(())
    }

    fn write_fx_borrowed_row<W: Write>(writer: &mut W, entry: &FxGainEntry) -> GenericResult<()> {
        let description = format!(
            "{} borrowed balance acquired {} ({})",
            entry.currency,
            Self::format_date(entry.acquisition_date),
            entry.activity_code
        );
        writeln!(
            writer,
            "FX Borrowed (review),{},,{},,{},,,,,,,{},,,,,,{}",
            Self::format_date(entry.date),
            Self::escape_csv(&entry.currency),
            Self::escape_csv(&description),
            Self::format_decimal(entry.amount_eur),
            Self::escape_csv(
                "Excluded from the savings base: repaying a currency loan is not clearly a \
                 transfer of a patrimonial element — review manually"
            )
        )?;
        Ok(())
    }

    fn write_fee_row<W: Write>(writer: &mut W, entry: &FeeEntry) -> GenericResult<()> {
        writeln!(
            writer,
            "Fee,{},{},,,{},,,,,,{},,,,,,{},{}",
            Self::format_date(entry.date),
            Self::format_date(entry.date),
            Self::escape_csv(&entry.description),
            Self::format_decimal(entry.amount_eur),
            if entry.deductible { "RCM" } else { "" },
            Self::escape_csv(entry.notes.as_deref().unwrap_or(""))
        )?;
        Ok(())
    }

    fn write_summary_rows<W: Write>(
        writer: &mut W,
        statement: &SpanishTaxStatement,
    ) -> GenericResult<()> {
        writeln!(writer)?;
        writeln!(
            writer,
            "# The cuota is computed once on the year's base after group compensation, NOT summed"
        )?;
        writeln!(
            writer,
            "# from the rows: the savings scale is progressive, so per-row taxes would not add up."
        )?;
        writeln!(writer, "summary_key,label,value_eur")?;

        let regime = match statement.regime {
            SpanishTaxRegime::Gipuzkoa => "Gipuzkoa (Norma Foral 3/2014)",
            SpanishTaxRegime::Comun => "Territorio Común (Ley 35/2006)",
        };
        writeln!(writer, "SUMMARY_REGIME,{regime},{}", statement.year)?;

        // A free function rather than a closure: the closure would hold the writer borrow for the
        // rest of the block, and the average-rate row below writes through the writer directly.
        fn row<W: Write>(
            writer: &mut W,
            key: &str,
            label: &str,
            value: Decimal,
        ) -> GenericResult<()> {
            writeln!(writer, "{key},{label},{}", CsvFormatter::format_decimal(value))?;
            Ok(())
        }

        row(
            writer,
            "SUMMARY_RCM_DIVIDENDS",
            "Dividendos (rendimientos del capital mobiliario)",
            statement.total_dividend_income,
        )?;
        row(
            writer,
            "SUMMARY_RCM_INTEREST",
            "Intereses (rendimientos del capital mobiliario)",
            statement.total_interest_income,
        )?;
        row(
            writer,
            "SUMMARY_RCM_DEDUCTIBLE_FEES",
            "Gastos deducibles de administración y depósito",
            statement.total_deductible_fees,
        )?;
        row(
            writer,
            "SUMMARY_RCM_NET",
            "Rendimiento neto del capital mobiliario",
            statement.rcm_net,
        )?;

        row(
            writer,
            "SUMMARY_GYP_CAPITAL_GAINS",
            "Ganancias y pérdidas por transmisión de valores",
            statement
                .capital_gains
                .iter()
                .map(|entry| entry.integrable_amount)
                .sum(),
        )?;
        row(
            writer,
            "SUMMARY_GYP_FX",
            "Ganancias y pérdidas por conversión de divisa",
            statement.total_fx_gains - statement.total_fx_losses,
        )?;
        row(
            writer,
            "SUMMARY_GYP_DEFERRED",
            "Pérdidas diferidas por valores homogéneos (no deducibles este año)",
            statement.total_deferred_loss,
        )?;
        row(
            writer,
            "SUMMARY_GYP_REINTEGRATED",
            "Pérdidas diferidas reintegradas al transmitirse los valores que las bloqueaban",
            statement.total_reintegrated_loss,
        )?;
        row(
            writer,
            "SUMMARY_GYP_NET",
            "Saldo de ganancias y pérdidas patrimoniales",
            statement.gyp_net,
        )?;

        row(
            writer,
            "SUMMARY_RCM_LOSSES_APPLIED",
            "Saldos negativos de ejercicios anteriores aplicados (RCM)",
            statement.rcm_applied.used_total,
        )?;
        row(
            writer,
            "SUMMARY_GYP_LOSSES_APPLIED",
            "Saldos negativos de ejercicios anteriores aplicados (ganancias)",
            statement.gyp_applied.used_total,
        )?;
        row(
            writer,
            "SUMMARY_CROSS_OFFSET_RCM_TO_GYP",
            "Compensación cruzada RCM → ganancias (25% — sólo Territorio Común)",
            statement.cross_offset_rcm_to_gyp,
        )?;
        row(
            writer,
            "SUMMARY_CROSS_OFFSET_GYP_TO_RCM",
            "Compensación cruzada ganancias → RCM (25% — sólo Territorio Común)",
            statement.cross_offset_gyp_to_rcm,
        )?;

        row(
            writer,
            "SUMMARY_RCM_TAXABLE",
            "RCM integrado en la base del ahorro",
            statement.rcm_taxable,
        )?;
        row(
            writer,
            "SUMMARY_GYP_TAXABLE",
            "Ganancias integradas en la base del ahorro",
            statement.gyp_taxable,
        )?;
        row(
            writer,
            "SUMMARY_SAVINGS_BASE",
            "Base liquidable del ahorro",
            statement.savings_base,
        )?;
        row(
            writer,
            "SUMMARY_SAVINGS_QUOTA",
            "Cuota íntegra del ahorro",
            statement.savings_quota,
        )?;

        // Not a EUR amount: printed at full precision because it is the multiplier behind the
        // credit cap, and rounding it would move the cap.
        writeln!(
            writer,
            "SUMMARY_AVERAGE_SAVINGS_RATE,Tipo medio de gravamen del ahorro (ratio — not EUR),{}",
            statement.average_savings_rate
        )?;

        row(
            writer,
            "SUMMARY_FOREIGN_WITHHOLDING",
            "Retenciones practicadas en el extranjero",
            statement.total_foreign_withholding,
        )?;
        row(
            writer,
            "SUMMARY_FOREIGN_TAX_CREDIT",
            "Deducción por doble imposición internacional",
            statement.total_foreign_tax_credit,
        )?;
        row(
            writer,
            "SUMMARY_NET_TAX_DUE",
            "Cuota líquida del ahorro",
            statement.net_tax_due,
        )?;

        row(
            writer,
            "SUMMARY_INFORMATIONAL_FEES",
            "Comisiones informativas (no deducibles)",
            statement.total_informational_fees,
        )?;
        row(
            writer,
            "SUMMARY_FX_BORROWED_REVIEW",
            "Resultados de divisa sobre saldo prestado (excluidos — revisión manual)",
            statement.total_fx_borrowed_review,
        )?;

        Ok(())
    }

    fn write_carryforward<W: Write>(
        writer: &mut W,
        statement: &SpanishTaxStatement,
    ) -> GenericResult<()> {
        let groups = [
            ("RCM", &statement.rcm_ledger_next, statement.rcm_expired),
            ("GYP", &statement.gyp_ledger_next, statement.gyp_expired),
        ];

        if groups
            .iter()
            .all(|(_, ledger, expired)| ledger.is_empty() && expired.is_zero())
        {
            return Ok(());
        }

        writeln!(writer)?;
        writeln!(
            writer,
            "# SALDOS NEGATIVOS PENDIENTES — put these in next year's taxes.spain.loss_carryforward,"
        )?;
        writeln!(
            writer,
            "# keyed by the year each arose in. A balance may be offset only in the four following"
        )?;
        writeln!(writer, "# years, so the origin year is part of the data.")?;

        for (group, ledger, expired) in groups {
            for (origin, amount) in ledger.balances() {
                writeln!(
                    writer,
                    "CARRYFORWARD_{group}_{origin},Saldo negativo pendiente — {group} — origen {origin},{}",
                    Self::format_decimal(*amount)
                )?;
            }
            if expired > Decimal::ZERO {
                writeln!(
                    writer,
                    "CARRYFORWARD_{group}_EXPIRED,Saldo negativo caducado sin usar ({group}),{}",
                    Self::format_decimal(expired)
                )?;
            }
        }

        Ok(())
    }

    fn write_deferred_losses<W: Write>(
        writer: &mut W,
        statement: &SpanishTaxStatement,
    ) -> GenericResult<()> {
        if statement.deferred_losses_next.is_empty() {
            return Ok(());
        }

        writeln!(writer)?;
        writeln!(
            writer,
            "# PÉRDIDAS DIFERIDAS PENDIENTES — put these in next year's taxes.spain.deferred_losses."
        )?;
        writeln!(
            writer,
            "# Each is a loss still blocked by homogeneous securities bought inside the two-month"
        )?;
        writeln!(
            writer,
            "# window and not yet disposed of; it becomes deductible as those shares are sold."
        )?;

        for (index, deferred) in statement.deferred_losses_next.iter().enumerate() {
            let label = format!(
                "{} — {} shares acquired {} blocking the loss of {}",
                deferred.symbol,
                deferred.blocked_quantity.normalize(),
                Self::format_date(deferred.acquisition_date),
                Self::format_date(deferred.sale_date)
            );
            writeln!(
                writer,
                "DEFERRED_LOSS_{index},{},{}",
                Self::escape_csv(&label),
                Self::format_decimal(deferred.loss)
            )?;
        }

        Ok(())
    }

    fn write_modelo_boxes<W: Write>(
        writer: &mut W,
        statement: &SpanishTaxStatement,
    ) -> GenericResult<()> {
        writeln!(writer)?;

        match statement.regime {
            SpanishTaxRegime::Gipuzkoa => {
                writeln!(writer, "# MODELO 109 — autoliquidación del IRPF de Gipuzkoa")?;
                writeln!(
                    writer,
                    "# WARNING: Gipuzkoa publishes no static numbered form — the return is generated"
                )?;
                writeln!(
                    writer,
                    "# by Zergabidea. The only official box map reachable is dated AÑO 2019, and the"
                )?;
                writeln!(
                    writer,
                    "# 2026 reform added a cuota-íntegra column plus a crypto section to Anexo 3,"
                )?;
                writeln!(
                    writer,
                    "# either of which plausibly renumbered boxes. Verify every casilla below against"
                )?;
                writeln!(writer, "# your filing year's own form before entering it.")?;

                let boxes = [
                    (
                        modelo_109::RCM_GROSS,
                        "Rendimientos íntegros del capital mobiliario",
                        statement.total_dividend_income + statement.total_interest_income,
                    ),
                    (
                        modelo_109::RCM_EXPENSES,
                        "Gastos deducibles del capital mobiliario",
                        statement.total_deductible_fees,
                    ),
                    (
                        modelo_109::RCM_WITHHOLDING,
                        "Retenciones del capital mobiliario",
                        statement.total_foreign_withholding,
                    ),
                    (
                        modelo_109::CAPITAL_GAINS,
                        "Ganancias y pérdidas patrimoniales (base del ahorro)",
                        statement.gyp_net,
                    ),
                    (
                        modelo_109::SAVINGS_BASE,
                        "Base imponible del ahorro",
                        statement.savings_base,
                    ),
                    (
                        modelo_109::NET_QUOTA,
                        "Cuota líquida",
                        statement.net_tax_due,
                    ),
                ];

                for (casilla, label, value) in boxes {
                    writeln!(
                        writer,
                        "MODELO_109_CASILLA_{casilla},{label} (casilla {casilla}),{}",
                        Self::format_decimal(value)
                    )?;
                }

                writeln!(
                    writer,
                    "# WARNING: the casilla for the deducción por doble imposición internacional is"
                )?;
                writeln!(
                    writer,
                    "# not published anywhere reachable, for any year. Locate it on the form yourself."
                )?;
                writeln!(
                    writer,
                    "MODELO_109_CASILLA_UNKNOWN,Deducción por doble imposición internacional (casilla unknown),{}",
                    Self::format_decimal(statement.total_foreign_tax_credit)
                )?;
            }
            SpanishTaxRegime::Comun => {
                writeln!(writer, "# MODELO 100 — declaración del IRPF (AEAT)")?;
                writeln!(
                    writer,
                    "# WARNING: Modelo 100's box layout was not verified for this tool, so no casilla"
                )?;
                writeln!(
                    writer,
                    "# numbers are given. Match each label against the AEAT form for your filing year."
                )?;

                let boxes = [
                    (
                        "RCM_GROSS",
                        "Rendimientos íntegros del capital mobiliario",
                        statement.total_dividend_income + statement.total_interest_income,
                    ),
                    (
                        "RCM_EXPENSES",
                        "Gastos de administración y depósito (art. 26.1.a)",
                        statement.total_deductible_fees,
                    ),
                    (
                        "RCM_WITHHOLDING",
                        "Retenciones practicadas en el extranjero",
                        statement.total_foreign_withholding,
                    ),
                    (
                        "CAPITAL_GAINS",
                        "Ganancias y pérdidas patrimoniales (base del ahorro)",
                        statement.gyp_net,
                    ),
                    (
                        "SAVINGS_BASE",
                        "Base liquidable del ahorro",
                        statement.savings_base,
                    ),
                    (
                        "FOREIGN_TAX_CREDIT",
                        "Deducción por doble imposición internacional",
                        statement.total_foreign_tax_credit,
                    ),
                    ("NET_QUOTA", "Cuota líquida del ahorro", statement.net_tax_due),
                ];

                for (key, label, value) in boxes {
                    writeln!(
                        writer,
                        "MODELO_100_{key},{label} (casilla unverified),{}",
                        Self::format_decimal(value)
                    )?;
                }
            }
        }

        Ok(())
    }

    fn write_warnings<W: Write>(
        writer: &mut W,
        statement: &SpanishTaxStatement,
    ) -> GenericResult<()> {
        if !statement.wash_sale_window_gaps.is_empty() {
            writeln!(writer)?;
            writeln!(
                writer,
                "# WARNING: valores-homogéneos window still open when the statement ends. A"
            )?;
            writeln!(
                writer,
                "# repurchase up to two months after the sale defers the loss, and one made after"
            )?;
            writeln!(
                writer,
                "# the statement's last date cannot be seen — so the losses below are deducted in"
            )?;
            writeln!(
                writer,
                "# FULL and may be OVERSTATED. Re-run once the statement covers the window."
            )?;
            for gap in &statement.wash_sale_window_gaps {
                let label = format!(
                    "{} sold {} — window open until {}",
                    gap.symbol,
                    Self::format_date(gap.sale_date),
                    Self::format_date(gap.window_end)
                );
                writeln!(
                    writer,
                    "WASH_SALE_WINDOW_OPEN,{},{}",
                    Self::escape_csv(&label),
                    Self::format_decimal(gap.loss_eur)
                )?;
            }
        }

        if !statement.wash_sale_unpriced_years.is_empty() {
            let years = statement
                .wash_sale_unpriced_years
                .iter()
                .map(i32::to_string)
                .collect::<Vec<_>>()
                .join(", ");
            writeln!(writer)?;
            writeln!(
                writer,
                "# WARNING: sales in {years} were not tested for the valores-homogéneos rule: no"
            )?;
            writeln!(
                writer,
                "# actualization table is shipped for those disposal years, so their result could"
            )?;
            writeln!(
                writer,
                "# not be priced. Set taxes.spain.coefficients.<year>, or carry the deferral in"
            )?;
            writeln!(writer, "# taxes.spain.deferred_losses from that year's return.")?;
        }

        if !statement.short_positions.is_empty() {
            writeln!(writer)?;
            writeln!(
                writer,
                "# SHORT POSITIONS — no tax is computed for these; they need manual review."
            )?;
            for (symbol, quantity) in &statement.short_positions {
                writeln!(
                    writer,
                    "SHORT_POSITION,{},{}",
                    Self::escape_csv(&format!("{symbol} — open short quantity (manual review)")),
                    Self::format_decimal(*quantity)
                )?;
            }
        }

        Ok(())
    }

    /// Round a reported figure to two places, half away from zero, through the module-shared
    /// formatter so the CSV and the console cannot disagree by a rounding cent.
    fn format_decimal(value: Decimal) -> String {
        super::format_eur(value)
    }

    /// Dates go out as ISO 8601, not in the `DD.MM.YYYY` form the rest of the tool prints, so the
    /// carry-out block round-trips straight back into `taxes.spain.deferred_losses`.
    fn format_date(date: crate::types::Date) -> String {
        date.format("%Y-%m-%d").to_string()
    }

    /// Coefficients are published to three decimals by the Decreto Foral; print them as published
    /// so a reader can match the cell against the table.
    fn format_coefficient(value: Decimal) -> String {
        let mut value = value;
        value.rescale(3);
        value.to_string()
    }

    fn escape_csv(value: &str) -> String {
        if value.contains(',') || value.contains('"') || value.contains('\n') {
            format!("\"{}\"", value.replace('"', "\"\""))
        } else {
            value.to_string()
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::taxes::spain::carryforward::LossLedger;
    use crate::taxes::spain::scale::SavingsScale;
    use crate::types::Date;

    const COLUMNS: usize = 19;

    fn date() -> Date {
        Date::from_ymd_opt(2026, 4, 15).unwrap()
    }

    fn render(write: impl FnOnce(&mut Vec<u8>) -> GenericResult<()>) -> String {
        let mut buf = Vec::new();
        write(&mut buf).unwrap();
        String::from_utf8(buf).unwrap().trim_end().to_string()
    }

    fn statement(regime: SpanishTaxRegime) -> SpanishTaxStatement {
        SpanishTaxStatement::new(
            2026,
            regime,
            SavingsScale::for_year(regime, 2026).unwrap(),
            LossLedger::default(),
            LossLedger::default(),
            Decimal::ZERO,
            dec!(0.15),
        )
    }

    fn capital_gain() -> CapitalGainEntry {
        CapitalGainEntry {
            symbol: "AAPL".to_string(),
            isin: "US0378331005".to_string(),
            description: "APPLE INC".to_string(),
            sale_date: date(),
            settle_date: date(),
            quantity: dec!(100),
            proceeds_eur: dec!(22500),
            cost_eur: dec!(9000),
            actualized_cost_eur: dec!(10908),
            fiscal_gain_loss: dec!(11592),
            deferred_loss: Decimal::ZERO,
            integrable_amount: dec!(11592),
            lots: vec![SpanishLotDetail {
                acquisition_date: Date::from_ymd_opt(2021, 3, 10).unwrap(),
                quantity: dec!(100),
                cost_eur: dec!(9000),
                coefficient: dec!(1.212),
                actualized_cost_eur: dec!(10908),
                proceeds_eur: dec!(22500),
                gain_eur: dec!(11592),
            }],
            notes: None,
        }
    }

    /// Every transaction and lot row carries the full 19-column shape and leaves inapplicable
    /// cells empty rather than filling them with a misleading 0.00 or an "N/A" placeholder.
    #[test]
    fn transaction_rows_are_19_columns_without_na() {
        let entry = capital_gain();
        let rows = [
            render(|w| CsvFormatter::write_capital_gain_row(w, &entry)),
            render(|w| CsvFormatter::write_lot_row(w, &entry, &entry.lots[0])),
            render(|w| CsvFormatter::write_reintegration_row(w, &reintegration())),
            render(|w| {
                CsvFormatter::write_dividend_row(
                    w,
                    &DividendEntry {
                        symbol: "AAPL".to_string(),
                        isin: "US0378331005".to_string(),
                        description: "AAPL CASH DIVIDEND".to_string(),
                        date: date(),
                        gross_eur: dec!(900),
                        withheld_eur: dec!(270),
                        treaty_capped_credit: dec!(135),
                    },
                )
            }),
            render(|w| {
                CsvFormatter::write_interest_row(
                    w,
                    &InterestEntry {
                        date: date(),
                        description: "Broker interest".to_string(),
                        gross_eur: dec!(90),
                    },
                )
            }),
            render(|w| {
                CsvFormatter::write_fx_gain_row(
                    w,
                    &FxGainEntry {
                        date: date(),
                        currency: "USD".to_string(),
                        acquisition_date: date(),
                        amount_eur: dec!(1000),
                        activity_code: "SELL".to_string(),
                    },
                )
            }),
            render(|w| {
                CsvFormatter::write_fx_borrowed_row(
                    w,
                    &FxGainEntry {
                        date: date(),
                        currency: "USD".to_string(),
                        acquisition_date: date(),
                        amount_eur: dec!(-40),
                        activity_code: "BUY".to_string(),
                    },
                )
            }),
            render(|w| {
                CsvFormatter::write_fee_row(
                    w,
                    &FeeEntry {
                        date: date(),
                        description: "CUSTODY FEE".to_string(),
                        amount_eur: dec!(45),
                        deductible: false,
                        notes: Some("Informational".to_string()),
                    },
                )
            }),
        ];

        let header = render(CsvFormatter::write_header);
        assert_eq!(header.split(',').count(), COLUMNS);

        for row in &rows {
            assert_eq!(row.split(',').count(), COLUMNS, "wrong column count: {row}");
            assert!(!row.contains("N/A"), "row emits an N/A placeholder: {row}");
        }
    }

    fn reintegration() -> WashSaleReintegrationEntry {
        WashSaleReintegrationEntry {
            symbol: "AAPL".to_string(),
            isin: "US0378331005".to_string(),
            date: Date::from_ymd_opt(2026, 11, 15).unwrap(),
            acquisition_date: Date::from_ymd_opt(2026, 4, 20).unwrap(),
            origin_sale_date: Date::from_ymd_opt(2026, 3, 10).unwrap(),
            released_eur: dec!(225),
        }
    }

    /// A released deferral is a loss becoming deductible, so it must enter the ganancias group as a
    /// **negative** amount — reported as a positive magnitude it would be added to the base instead.
    #[test]
    fn a_reintegration_enters_the_group_as_a_negative_amount() {
        let header = render(CsvFormatter::write_header);
        let columns: Vec<String> = header.split(',').map(str::to_string).collect();
        let row = render(|w| CsvFormatter::write_reintegration_row(w, &reintegration()));

        let cell = |name: &str| -> String {
            let index = columns.iter().position(|column| column == name).unwrap();
            row.split(',').nth(index).unwrap().to_string()
        };

        assert_eq!(cell("gain_loss_eur"), "-225.00");
        assert_eq!(cell("integrable_amount_eur"), "-225.00");
        assert_eq!(cell("savings_group"), "GyP");
        // Dated to the disposal that released it, not to the sale it came from.
        assert_eq!(cell("transaction_date"), "2026-11-15");
        assert!(row.contains("2026-03-10"), "the origin sale must be named: {row}");
    }

    /// Surviving blocked lots are printed in the shape next year's config takes, keyed so the filer
    /// can copy them straight into `taxes.spain.deferred_losses`.
    #[test]
    fn surviving_deferrals_are_printed_as_next_years_config() {
        let mut spain = statement(SpanishTaxRegime::Gipuzkoa);
        spain.deferred_losses_next = vec![crate::taxes::DeferredLossConfig {
            symbol: "AAPL".to_string(),
            isin: Some("US0378331005".to_string()),
            loss: dec!(135),
            blocked_quantity: dec!(15),
            acquisition_date: Date::from_ymd_opt(2026, 4, 20).unwrap(),
            sale_date: Date::from_ymd_opt(2026, 3, 10).unwrap(),
        }];

        let output = render(|w| CsvFormatter::write_deferred_losses(w, &spain));
        let row = output
            .lines()
            .find(|line| line.starts_with("DEFERRED_LOSS_0,"))
            .expect("carry-out row present");

        let mut reader = csv::ReaderBuilder::new()
            .has_headers(false)
            .from_reader(row.as_bytes());
        let record = reader.records().next().unwrap().unwrap();
        assert_eq!(record.len(), 3, "must stay in the 3-column summary block: {row}");
        assert!(record[1].contains("15 shares acquired 2026-04-20"));
        assert!(record[1].contains("2026-03-10"));
        assert_eq!(&record[2], "135.00");

        // Nothing blocked, nothing printed.
        let empty = render(|w| {
            CsvFormatter::write_deferred_losses(w, &statement(SpanishTaxRegime::Gipuzkoa))
        });
        assert!(empty.is_empty());
    }

    /// A loss whose repurchase window outlives the statement is deducted in full, so the file has to
    /// say the figure may be overstated rather than presenting it as settled.
    #[test]
    fn an_open_wash_sale_window_is_warned_about() {
        let mut spain = statement(SpanishTaxRegime::Gipuzkoa);
        spain.wash_sale_window_gaps = vec![super::super::statement::WashSaleWindowGap {
            symbol: "AAPL".to_string(),
            sale_date: Date::from_ymd_opt(2026, 12, 15).unwrap(),
            window_end: Date::from_ymd_opt(2027, 2, 15).unwrap(),
            loss_eur: dec!(900),
        }];

        let output = render(|w| CsvFormatter::write_warnings(w, &spain));
        assert!(output.contains("# WARNING"));
        assert!(output.contains("OVERSTATED"));
        let row = output
            .lines()
            .find(|line| line.starts_with("WASH_SALE_WINDOW_OPEN,"))
            .expect("window row present");
        assert_eq!(row.split(',').count(), 3, "{row}");
        assert!(row.contains("2027-02-15"));
    }

    /// Each value must land in the column the header names it by, or a consumer summing a named
    /// column double-counts. The coefficient in particular belongs to the lot row only.
    #[test]
    fn values_land_in_their_named_columns() {
        let header = render(CsvFormatter::write_header);
        let columns: Vec<String> = header.split(',').map(str::to_string).collect();
        let cell = |row: &str, name: &str| -> String {
            let index = columns
                .iter()
                .position(|column| column == name)
                .expect("column present");
            row.split(',').nth(index).expect("cell present").to_string()
        };

        let entry = capital_gain();
        let sale = render(|w| CsvFormatter::write_capital_gain_row(w, &entry));
        assert_eq!(cell(&sale, "cost_eur"), "9000.00");
        assert_eq!(cell(&sale, "actualized_cost_eur"), "10908.00");
        assert_eq!(cell(&sale, "gain_loss_eur"), "11592.00");
        assert_eq!(cell(&sale, "integrable_amount_eur"), "11592.00");
        assert_eq!(cell(&sale, "savings_group"), "GyP");
        assert_eq!(
            cell(&sale, "coefficient"),
            "",
            "a sale can consume lots of several vintages, so it has no single coefficient"
        );
        assert_eq!(cell(&sale, "gross_amount_eur"), "");

        let lot = render(|w| CsvFormatter::write_lot_row(w, &entry, &entry.lots[0]));
        assert_eq!(cell(&lot, "coefficient"), "1.212");
        assert_eq!(cell(&lot, "transaction_date"), "2021-03-10");
        assert_eq!(cell(&lot, "actualized_cost_eur"), "10908.00");

        let dividend = render(|w| {
            CsvFormatter::write_dividend_row(
                w,
                &DividendEntry {
                    symbol: "AAPL".to_string(),
                    isin: String::new(),
                    description: "dividend".to_string(),
                    date: date(),
                    gross_eur: dec!(900),
                    withheld_eur: dec!(270),
                    treaty_capped_credit: dec!(135),
                },
            )
        });
        assert_eq!(cell(&dividend, "gross_amount_eur"), "900.00");
        assert_eq!(cell(&dividend, "foreign_tax_eur"), "270.00");
        assert_eq!(cell(&dividend, "treaty_capped_credit_eur"), "135.00");
        assert_eq!(cell(&dividend, "savings_group"), "RCM");
        assert_eq!(cell(&dividend, "quantity"), "");
        assert_eq!(cell(&dividend, "gain_loss_eur"), "");
    }

    /// A deductible fee is marked as reaching the RCM group; a non-deductible one carries no group,
    /// so a consumer cannot mistake an informational row for a deduction.
    #[test]
    fn fee_group_reflects_deductibility() {
        let fee = |deductible| FeeEntry {
            date: date(),
            description: "CUSTODY FEE".to_string(),
            amount_eur: dec!(45),
            deductible,
            notes: None,
        };

        let deductible = render(|w| CsvFormatter::write_fee_row(w, &fee(true)));
        assert_eq!(deductible.split(',').nth(17), Some("RCM"));

        let informational = render(|w| CsvFormatter::write_fee_row(w, &fee(false)));
        assert_eq!(informational.split(',').nth(17), Some(""));
    }

    /// A description containing a comma must not split the row: the cell is escaped as a unit, so
    /// a quote-aware parser still reads 19 fields with the comma preserved.
    #[test]
    fn commas_inside_a_cell_stay_one_field() {
        let mut entry = capital_gain();
        entry.description = "APPLE INC, CLASS A".to_string();

        let row = render(|w| CsvFormatter::write_capital_gain_row(w, &entry));
        let mut reader = csv::ReaderBuilder::new()
            .has_headers(false)
            .from_reader(row.as_bytes());
        let record = reader.records().next().unwrap().unwrap();
        assert_eq!(record.len(), COLUMNS, "escaped comma broke the field count");
        assert_eq!(&record[5], "APPLE INC, CLASS A");
    }

    /// Reported figures round half away from zero, never truncate: `{:.2}` on a Decimal truncates
    /// and would understate a cent on a tax form.
    #[test]
    fn format_decimal_rounds_half_away_from_zero() {
        assert_eq!(CsvFormatter::format_decimal(dec!(0.518)), "0.52");
        assert_eq!(CsvFormatter::format_decimal(dec!(-0.125)), "-0.13");
        assert_eq!(CsvFormatter::format_decimal(dec!(2)), "2.00");
    }

    /// Coefficients are printed to three decimals exactly as the Decreto Foral publishes them, so a
    /// reader can match the cell against the official table without mental rescaling.
    #[test]
    fn coefficients_print_at_the_published_precision() {
        assert_eq!(CsvFormatter::format_coefficient(dec!(1.212)), "1.212");
        assert_eq!(CsvFormatter::format_coefficient(dec!(1)), "1.000");
        assert_eq!(CsvFormatter::format_coefficient(dec!(1.05)), "1.050");
    }

    /// The summary block is its own 3-column section: a row that spilled a comma would break any
    /// comma-delimited import of the block.
    #[test]
    fn summary_rows_are_three_columns() {
        let mut spain = statement(SpanishTaxRegime::Gipuzkoa);
        spain.capital_gains.push(capital_gain());
        spain.calculate_totals();

        let output = render(|w| CsvFormatter::write_summary_rows(w, &spain));
        let rows: Vec<&str> = output
            .lines()
            .filter(|line| line.starts_with("SUMMARY_"))
            .collect();

        assert!(rows.len() >= 15, "summary block looks truncated: {rows:?}");
        for row in rows {
            assert_eq!(
                row.split(',').count(),
                3,
                "summary row must stay within its 3 columns: {row}"
            );
        }
    }

    /// The Modelo box numbers are unverified for every supported year, so each regime's block must
    /// carry a warning banner rather than presenting a casilla as settled.
    #[test]
    fn modelo_boxes_are_emitted_under_a_warning() {
        let gipuzkoa = render(|w| {
            CsvFormatter::write_modelo_boxes(w, &statement(SpanishTaxRegime::Gipuzkoa))
        });
        assert!(gipuzkoa.contains("# MODELO 109"));
        assert!(gipuzkoa.contains("# WARNING"));
        assert!(gipuzkoa.contains("AÑO 2019"));
        assert!(gipuzkoa.contains("MODELO_109_CASILLA_33"));
        // The double-taxation casilla is unknown for every year; it must say so, not guess.
        assert!(gipuzkoa.contains("MODELO_109_CASILLA_UNKNOWN"));

        let comun =
            render(|w| CsvFormatter::write_modelo_boxes(w, &statement(SpanishTaxRegime::Comun)));
        assert!(comun.contains("# MODELO 100"));
        assert!(comun.contains("# WARNING"));
        assert!(!comun.contains("MODELO_109"));
    }

    /// Pending balances are printed keyed by origin year, because the four-year window is measured
    /// from it — an aggregate would lose the information next year's config needs.
    #[test]
    fn carryforward_is_keyed_by_origin_year() {
        let mut spain = statement(SpanishTaxRegime::Gipuzkoa);
        let mut loss = capital_gain();
        loss.fiscal_gain_loss = dec!(-9360);
        loss.integrable_amount = dec!(-9360);
        spain.capital_gains.push(loss);
        spain.calculate_totals();

        let output = render(|w| CsvFormatter::write_carryforward(w, &spain));
        assert!(
            output.contains("CARRYFORWARD_GYP_2026,"),
            "missing origin-year row: {output}"
        );
        for row in output
            .lines()
            .filter(|line| !line.starts_with('#') && !line.is_empty())
        {
            assert_eq!(row.split(',').count(), 3, "{row}");
        }

        // Nothing pending, nothing printed.
        let empty = render(|w| {
            CsvFormatter::write_carryforward(w, &statement(SpanishTaxRegime::Gipuzkoa))
        });
        assert!(empty.is_empty());
    }
}
