//! Where each figure goes on the return: Modelo 109 (Gipuzkoa), Modelo 100 (Territorio Común) and
//! Modelo F-93 (Navarra), plus the regime-dependent wording of the compensation and FX rows.
//!
//! One mapping serves every output. A casilla number, the caveat that qualifies it and the label
//! that names it are written once here, so the CSV and the printable report cannot send a filer to
//! two different boxes for the same amount.

use crate::taxes::spain::SpanishTaxRegime;
use crate::types::Decimal;

use super::statement::SpanishTaxStatement;

/// Modelo 109 box numbers, per ejercicio.
///
/// Gipuzkoa publishes no blank numbered form — the return is generated by the Zergabidea platform —
/// so the numbers are read off the Hacienda Foral "Propuesta de autoliquidación" specimens, one per
/// ejercicio (`gipuzkoa.eus/es/web/ogasuna/impuestos/modelo/109/<ejercicio>/propuesta-autoliquidacion`,
/// retrieved 2026-08-11).
///
/// The **Hoja de liquidación** numbering below is stable from ejercicio 2019 through 2025. The
/// deduction block is not: NF 1/2025 renumbered it for ejercicio 2025, moving the deducción por
/// doble imposición internacional from casilla 60 to 70 and the cuota líquida from 64 to 74.
///
/// **Anexo 3 is a different numbering space from the Hoja** — Hoja 28 is the rendimiento neto del
/// capital mobiliario while Anexo 4's own 28 is ganancias — and its internals are confirmed only
/// through ejercicio 2024; the 2025 specimen renumbers them. They are emitted for ejercicios up to
/// 2024 only, under keys that name the sheet they belong to.
mod modelo_109 {
    /// Rendimiento neto del capital mobiliario, base del ahorro.
    pub const HOJA_RCM_NET: &str = "28";
    pub const HOJA_RCM_COMPENSATION: &str = "29";
    /// Ganancias y pérdidas patrimoniales por transmisiones.
    pub const HOJA_CAPITAL_GAINS: &str = "30";
    pub const HOJA_GYP_COMPENSATION: &str = "31";
    pub const HOJA_SAVINGS_BASE: &str = "33";
    pub const HOJA_SAVINGS_QUOTA: &str = "38";

    pub const ANEXO3_RCM_GROSS: &str = "06+16";
    pub const ANEXO3_RCM_EXPENSES: &str = "17";
    /// Retenciones practicadas **en España**. Nothing the tool computes belongs here: an IB
    /// statement's withholding is foreign, and foreign tax is relieved through the deducción por
    /// doble imposición, never as a retención. Named so the warning can point at it.
    pub const ANEXO3_RCM_WITHHOLDING: &str = "07+22";

    /// The part of the form NF 1/2025 renumbered.
    pub struct Layout {
        /// Ejercicio the specimen these numbers come from covers.
        pub ejercicio: i32,
        pub double_taxation: &'static str,
        pub net_quota: &'static str,
        /// Pagos a cuenta del capital mobiliario — Spanish withholding only.
        pub rcm_prepayments: &'static str,
        /// Whether Anexo 3's internals are confirmed for this ejercicio.
        pub anexo3: bool,
    }

    const EJERCICIO_2024: Layout = Layout {
        ejercicio: 2024,
        double_taxation: "60",
        net_quota: "64",
        rcm_prepayments: "67",
        anexo3: true,
    };

    const EJERCICIO_2025: Layout = Layout {
        ejercicio: 2025,
        double_taxation: "70",
        net_quota: "74",
        rcm_prepayments: "77",
        anexo3: false,
    };

    /// The published layout for a filing year. Anything after 2025 gets the 2025 one: the form for a
    /// filing year is published with its campaign, so no later numbering exists yet.
    pub fn layout(year: i32) -> &'static Layout {
        if year <= 2024 {
            &EJERCICIO_2024
        } else {
            &EJERCICIO_2025
        }
    }
}

/// Modelo 100 box numbers for ejercicio 2025.
///
/// Read from Anexo I of **Orden HAC/277/2026, de 25 de marzo** (BOE-A-2026-7041, BOE núm. 76 of
/// 27-03-2026), the enacted order that approves the ejercicio-2025 models. Every casilla below
/// carries the same number in the ejercicio-2024 order (Orden HAC/242/2025, BOE-A-2025-5049, BOE
/// núm. 63 of 14-03-2025), so the two published years agree. Retrieved 2026-09-09 with
/// `pdftotext -layout`, which is what keeps a box number aligned with the label it belongs to.
mod modelo_100 {
    pub const INTEREST: &str = "0027";
    pub const DIVIDENDS: &str = "0029";
    pub const RCM_EXPENSES: &str = "0037";
    /// Ganancias y pérdidas por transmisión de acciones cotizadas: an itemized block, not one box.
    pub const LISTED_CAPITAL_GAINS: &str = "0326_0340";
    /// Base **imponible** del ahorro, i.e. the two groups after integración y compensación.
    ///
    /// The base *liquidable* is a different casilla — 0510 — and subtracts whatever is left of the
    /// reducciones por tributación conjunta, pensiones compensatorias y anualidades por alimentos
    /// (LIRPF art. 50). This tool models none of them, so what it computes is 0460; a filer who
    /// went looking for the box the word "liquidable" names would put it one step too late.
    pub const SAVINGS_BASE: &str = "0460";
    /// Named only so the label can point at it; nothing the tool computes belongs in it.
    pub const SAVINGS_BASE_AFTER_REDUCTIONS: &str = "0510";
    /// Where apartado F2 puts a transmission of anything other than a listed share: the sub-block
    /// "ganancias y pérdidas patrimoniales derivadas de transmisiones de otros elementos
    /// patrimoniales". The AEAT scopes it by exclusion — it does not reach the acciones cotizadas
    /// of the 0326-0340 block above it.
    ///
    /// 1624 is the sub-block's **first** casilla, and it is the owner selector ("contribuyente
    /// titular del elemento patrimonial transmitido"), not an amount. It is named so a filer can
    /// find the block on the page; nothing the tool computes goes in it.
    pub const OTHER_ELEMENTS: &str = "1624";
    /// Tipo de elemento patrimonial, the box that selects which kind of element the row describes.
    pub const OTHER_ELEMENTS_KIND: &str = "1626";
    /// The value of `OTHER_ELEMENTS_KIND` for "otros elementos patrimoniales **no afectos** a
    /// actividades económicas".
    ///
    /// Four, not five, and the difference is not cosmetic: clave 5 is the *afectos* one — business
    /// assets, "por ejemplo, licencia de taxi" — which routes the gain through the DA 7.ª reduction
    /// into casilla 0387 instead of the DT 9.ª path into 0386. Five is easy to reach for because it
    /// **was** this concept's number on the pre-restructuring form (ejercicios 2019-2021), before
    /// the AEAT split inmuebles into their own sub-block and renumbered the claves.
    pub const OTHER_ELEMENTS_PRIVATE_KEY: &str = "4";
    /// Per-element boxes of the sub-block, in the order the form asks for them.
    pub const OTHER_ELEMENTS_DISPOSAL_VALUE: &str = "1633";
    pub const OTHER_ELEMENTS_ACQUISITION_VALUE: &str = "1637";
    /// Pérdida obtenida, then the part imputable to the year; the latter is what 0385 sums.
    pub const OTHER_ELEMENTS_LOSS_IMPUTABLE: &str = "1639";
    /// Ganancia obtenida → no exenta → reducida no exenta → imputable; the last is what 0386 sums.
    pub const OTHER_ELEMENTS_GAIN_IMPUTABLE: &str = "1650";
    /// "Suma de pérdidas patrimoniales derivadas de transmisiones de otros elementos patrimoniales
    /// (suma de las casillas [1639])". Feeds casilla 0423 in apartado G.
    pub const OTHER_ELEMENTS_LOSSES: &str = "0385";
    /// "Suma de ganancias patrimoniales derivadas de transmisiones de otros elementos patrimoniales
    /// no afectos a actividades económicas (suma de las casillas [1650])". Feeds 0422.
    pub const OTHER_ELEMENTS_GAINS: &str = "0386";
    pub const FOREIGN_TAX_CREDIT: &str = "0588";
    /// Retenciones del capital mobiliario — Spanish withholding only. See `modelo_109::RCM_WITHHOLDING`.
    pub const RCM_WITHHOLDING: &str = "0597";
}

/// Modelo F-93 box numbers, read from the fully numbered form the Boletín Oficial de Navarra
/// publishes as Anexo I of each campaign's Orden Foral.
///
/// Verified against the ejercicio-2025 specimen (Orden Foral 24/2026, BON nº 66 of 07-04-2026),
/// retrieved 2026-08-12. Where the form states its own arithmetic the constants below reproduce it,
/// so a wrong mapping shows up as a sum that does not close rather than as a plausible number.
mod modelo_f93 {
    /// Ejercicio whose specimen these numbers were read from.
    pub const VERIFIED_EJERCICIO: i32 = 2025;

    /// Página 2, rendimientos del capital mobiliario — parte especial del ahorro.
    pub const RCM_DIVIDENDS: &str = "031";
    pub const RCM_INTEREST: &str = "037";
    pub const RCM_EXPENSES: &str = "047";
    pub const RCM_NET: &str = "050";
    /// Total retenciones del capital mobiliario — Spanish withholding only, and one of the
    /// components of casilla 579. Named so the warning can point at it; never emitted as a row.
    pub const RCM_WITHHOLDING: &str = "030 (suma en 579)";

    /// Anexo 1, transmisiones: the "incremento o disminución PARTE ESPECIAL DEL AHORRO" column
    /// total, and the per-transmission "incremento exento, otros supuestos" cells the art. 39.5.d
    /// relief is entered in.
    pub const TRANSFERS_TOTAL: &str = "706";
    pub const TRANSFERS_EXEMPT: &str = "1658-1672";

    /// Anexo 2, apartado H — resumen de la parte especial del ahorro.
    pub const H1_TRANSFERS_POSITIVE: &str = "8808";
    pub const H1_OWN_LOSSES: &str = "809";
    pub const H1_RCM_LOSSES_CROSSED: &str = "8815";
    pub const H1_NET: &str = "8809";
    pub const H2_RCM_POSITIVE: &str = "8810";
    pub const H2_OWN_LOSSES: &str = "8825";
    pub const H2_TRANSFER_LOSSES_CROSSED: &str = "8805";
    pub const H2_NET: &str = "8840";
    /// Apartado H3's own saldo, the mirror image of H4's 8850. The specimen's box column carries
    /// 8816 / 817 / 818 against H3's three lines exactly as it carries 8850 / 8865 / 8875 against
    /// H4's, and 8816 sits on the H3 line itself. Read from the ejercicio-2025 specimen only, like
    /// every other number here.
    pub const H3_TRANSFERS_NEGATIVE: &str = "8816";
    pub const H4_RCM_NEGATIVE: &str = "8850";
    pub const TOTAL: &str = "8841";
    /// Base and cuota, each with the página-7 summary box that repeats it.
    pub const SAVINGS_BASE: &str = "815 (= 524)";
    pub const SAVINGS_QUOTA: &str = "829 (= 527)";
    /// Saldos negativos a compensar en los ejercicios siguientes.
    pub const TRANSFERS_CARRYFORWARD: &str = "818";
    pub const RCM_CARRYFORWARD: &str = "8875";

    /// Deducción por doble imposición internacional. **Not** 613, which is the transparencia fiscal
    /// internacional deduction and a different relief entirely.
    pub const FOREIGN_TAX_CREDIT: &str = "572";
}

/// One casilla of the filer's return, with the amount that goes in it.
pub(super) struct FormBox {
    /// Stable key the CSV row is named by, e.g. `MODELO_109_HOJA_28`.
    pub key: String,
    /// Form the casilla belongs to, as the filer knows it.
    pub form: &'static str,
    /// Casilla as the form prints it: a number, a sum of two (`06+16`), a range, or a number with
    /// the box that repeats it.
    pub casilla: String,
    /// Sheet the casilla lives on where the form has more than one numbering space (`hoja`,
    /// `anexo 3`); empty otherwise.
    pub sheet: &'static str,
    /// What the form calls the amount.
    pub concept: String,
    pub value: Decimal,
}

impl FormBox {
    fn new(
        key_prefix: &str,
        form: &'static str,
        sheet: &'static str,
        casilla: &str,
        concept: &str,
        value: Decimal,
    ) -> FormBox {
        FormBox {
            key: format!("{key_prefix}{casilla}"),
            form,
            casilla: casilla.to_owned(),
            sheet,
            concept: concept.to_owned(),
            value,
        }
    }

    /// The label the CSV prints: the concept, plus the sheet and casilla where the form numbers
    /// more than one space and the bare concept would not say which one.
    pub fn label(&self) -> String {
        if self.sheet.is_empty() {
            self.concept.clone()
        } else {
            format!(
                "{} ({}, casilla {})",
                self.concept, self.sheet, self.casilla
            )
        }
    }
}

/// Every casilla of one regime's return, with the caveats that qualify it.
///
/// The header and footer lines are stored one per printed line, exactly as the CSV breaks them: the
/// CSV prefixes each with `# `, and the report joins them into prose.
pub(super) struct FormMapping {
    pub title: &'static str,
    pub header_lines: Vec<String>,
    pub boxes: Vec<FormBox>,
    pub footer_lines: Vec<String>,
    /// The retenciones casilla foreign withholding must **not** be entered in.
    pub withholding_casilla: String,
}

/// The return the regime files, as the filer knows it.
pub(super) fn form_name(regime: SpanishTaxRegime) -> &'static str {
    match regime {
        SpanishTaxRegime::Gipuzkoa => "Modelo 109",
        SpanishTaxRegime::Comun => "Modelo 100",
        SpanishTaxRegime::Navarra => "Modelo F-93",
    }
}

/// The casillas of the filer's own return.
pub(super) fn form_mapping(statement: &SpanishTaxStatement) -> FormMapping {
    match statement.regime {
        SpanishTaxRegime::Gipuzkoa => modelo_109_mapping(statement),
        SpanishTaxRegime::Comun => modelo_100_mapping(statement),
        SpanishTaxRegime::Navarra => modelo_f93_mapping(statement),
    }
}

fn modelo_109_mapping(statement: &SpanishTaxStatement) -> FormMapping {
    let layout = modelo_109::layout(statement.year);

    let mut header_lines = vec![
        "The numbers below are read off the Hacienda Foral \"Propuesta de autoliquidación\""
            .to_owned(),
        format!(
            "specimen for ejercicio {} (gipuzkoa.eus/es/web/ogasuna/impuestos/modelo/109/,",
            layout.ejercicio
        ),
        "retrieved 2026-08-11). Gipuzkoa publishes no blank numbered form — the return".to_owned(),
        "is generated by Zergabidea — so check each casilla against your own proposal.".to_owned(),
    ];

    if statement.year > layout.ejercicio {
        header_lines.push(format!(
            "WARNING: no form is published for ejercicio {} yet — it is filed in {}.",
            statement.year,
            statement.year + 1
        ));
        header_lines.push(format!(
            "These are the ejercicio-{} numbers, the last published layout.",
            layout.ejercicio
        ));
    }

    let mut boxes = Vec::new();

    if layout.anexo3 {
        for (casilla, concept, value) in [
            (
                modelo_109::ANEXO3_RCM_GROSS,
                "Rendimientos íntegros del capital mobiliario (excluida la renta exenta)",
                statement.declarable_rcm_income(),
            ),
            (
                modelo_109::ANEXO3_RCM_EXPENSES,
                "Gastos deducibles del capital mobiliario",
                statement.total_deductible_fees,
            ),
        ] {
            boxes.push(FormBox::new(
                "MODELO_109_ANEXO3_",
                form_name(SpanishTaxRegime::Gipuzkoa),
                "anexo 3",
                casilla,
                concept,
                value,
            ));
        }
    } else {
        header_lines.extend(
            [
                "WARNING: the rendimientos íntegros / gastos breakdown lives in Anexo 3,",
                "whose internal numbering is confirmed only through ejercicio 2024 and was",
                "renumbered by NF 1/2025. Only the Hoja de liquidación rows are emitted",
                "here; take the breakdown from your own Anexo 3.",
            ]
            .map(str::to_owned),
        );
    }

    for (casilla, concept, value) in [
        (
            modelo_109::HOJA_RCM_NET,
            "Rendimiento neto del capital mobiliario (base del ahorro)",
            statement.rcm_net,
        ),
        (
            modelo_109::HOJA_RCM_COMPENSATION,
            "Compensación de rendimientos negativos de ejercicios anteriores",
            statement.rcm_own_group_losses_applied(),
        ),
        (
            modelo_109::HOJA_CAPITAL_GAINS,
            "Ganancias y pérdidas patrimoniales por transmisiones",
            statement.gyp_net,
        ),
        (
            modelo_109::HOJA_GYP_COMPENSATION,
            "Compensación de pérdidas de ejercicios anteriores",
            statement.gyp_own_group_losses_applied(),
        ),
        (
            modelo_109::HOJA_SAVINGS_BASE,
            "Base liquidable del ahorro (tras compensación)",
            statement.savings_base,
        ),
        (
            modelo_109::HOJA_SAVINGS_QUOTA,
            "Cuota íntegra del ahorro",
            statement.savings_quota,
        ),
        (
            layout.double_taxation,
            "Deducción por doble imposición internacional",
            statement.total_foreign_tax_credit,
        ),
        (
            layout.net_quota,
            "Cuota líquida del ahorro",
            statement.net_tax_due,
        ),
    ] {
        boxes.push(FormBox::new(
            "MODELO_109_HOJA_",
            form_name(SpanishTaxRegime::Gipuzkoa),
            "hoja",
            casilla,
            concept,
            value,
        ));
    }

    // Both sheets carry a retenciones box, and the filer sees whichever one the form puts in front
    // of them, so name the ones that exist for the year.
    let withholding_casilla = if layout.anexo3 {
        format!(
            "{} (hoja) / {} (anexo 3)",
            layout.rcm_prepayments,
            modelo_109::ANEXO3_RCM_WITHHOLDING
        )
    } else {
        format!("{} (hoja)", layout.rcm_prepayments)
    };

    FormMapping {
        title: "MODELO 109 — autoliquidación del IRPF de Gipuzkoa",
        header_lines,
        boxes,
        footer_lines: Vec::new(),
        withholding_casilla,
    }
}

fn modelo_100_mapping(statement: &SpanishTaxStatement) -> FormMapping {
    // A currency conversion transmits a patrimonial element that is not a listed share, so its
    // result belongs to the otros-elementos sub-block of apartado F2 rather than to 0326-0340.
    // Both sums go in, not the net: the form keeps gains and losses in separate boxes that feed
    // casillas 0422 and 0423 separately.
    let has_conversions = !statement.fx_gains.is_empty();
    let other_elements: Vec<(&str, String, Decimal)> = if !has_conversions {
        Vec::new()
    } else {
        vec![
            (
                modelo_100::OTHER_ELEMENTS_GAINS,
                "Suma de ganancias por transmisión de otros elementos patrimoniales no afectos \
                 (conversiones de divisa)"
                    .to_owned(),
                statement.total_fx_gains,
            ),
            (
                modelo_100::OTHER_ELEMENTS_LOSSES,
                "Suma de pérdidas por transmisión de otros elementos patrimoniales (conversiones \
                 de divisa)"
                    .to_owned(),
                statement.total_fx_losses,
            ),
        ]
    };

    // In form order: the two RCM boxes, the deductible expense, the shares block, the otros-
    // elementos sums that follow it on the page, then the base and the deduction.
    let boxes = [
        (
            modelo_100::INTEREST,
            "Intereses de cuentas y depósitos (rendimientos del capital mobiliario)".to_owned(),
            statement.total_interest_income,
        ),
        (
            modelo_100::DIVIDENDS,
            "Dividendos y participaciones en beneficios (excluida la renta exenta)".to_owned(),
            statement.total_dividend_income - statement.total_dividend_exemption,
        ),
        (
            modelo_100::RCM_EXPENSES,
            "Gastos de administración y depósito (art. 26.1.a)".to_owned(),
            statement.total_deductible_fees,
        ),
        (
            modelo_100::LISTED_CAPITAL_GAINS,
            "Ganancias y pérdidas por transmisión de acciones cotizadas (casillas 0326-0340; \
             excluye el resultado de divisa)"
                .to_owned(),
            // The block is *acciones cotizadas* only. A currency conversion is a transmisión too
            // (LIRPF art. 33) but not of a listed share, so its result is taken out here and posted
            // to the otros-elementos sums below; leaving it in would put a figure in 0326-0340 that
            // the AEAT's own scoping of that block excludes.
            statement.gyp_net - statement.total_fx_result,
        ),
    ]
    .into_iter()
    .chain(other_elements)
    .chain([
        (
            modelo_100::SAVINGS_BASE,
            format!(
                "Base imponible del ahorro (tras compensación) — la base liquidable es la casilla \
                 {} y resta el remanente de reducciones que esta herramienta no calcula",
                modelo_100::SAVINGS_BASE_AFTER_REDUCTIONS
            ),
            statement.savings_base,
        ),
        (
            modelo_100::FOREIGN_TAX_CREDIT,
            "Deducción por doble imposición internacional".to_owned(),
            statement.total_foreign_tax_credit,
        ),
    ])
    .map(|(casilla, concept, value)| {
        FormBox::new(
            "MODELO_100_",
            form_name(SpanishTaxRegime::Comun),
            "",
            casilla,
            &concept,
            value,
        )
    })
    .collect();

    // The two sums above are the only figures of the sub-block the tool can fill: the rest of it is
    // per-element (one set of boxes per conversion, with its own dates and values), and the tool
    // does not know how a filer wants to group a year of conversions into elements. So the footer
    // names the boxes each row needs rather than pretending a total can stand in for them.
    let footer_lines = if !has_conversions {
        Vec::new()
    } else {
        vec![
            format!(
                "The {} EUR of foreign-currency results above are transmissions of a patrimonial",
                super::format_eur(statement.total_fx_result)
            ),
            "element (LIRPF art. 33), not of a listed share, so they go in apartado F2 under"
                .to_owned(),
            format!(
                "\"otros elementos patrimoniales\" ({} onwards), with clave {} = {} in casilla {}.",
                modelo_100::OTHER_ELEMENTS,
                modelo_100::OTHER_ELEMENTS_PRIVATE_KEY,
                "otros elementos no afectos a actividades económicas",
                modelo_100::OTHER_ELEMENTS_KIND,
            ),
            format!(
                "The block is itemized: enter each conversion with its valor de transmisión ({}),",
                modelo_100::OTHER_ELEMENTS_DISPOSAL_VALUE
            ),
            format!(
                "valor de adquisición ({}) and result ({} for a loss, {} for a gain). The two",
                modelo_100::OTHER_ELEMENTS_ACQUISITION_VALUE,
                modelo_100::OTHER_ELEMENTS_LOSS_IMPUTABLE,
                modelo_100::OTHER_ELEMENTS_GAIN_IMPUTABLE,
            ),
            format!(
                "sums posted above ({} and {}) are what those per-row boxes must add up to.",
                modelo_100::OTHER_ELEMENTS_GAINS,
                modelo_100::OTHER_ELEMENTS_LOSSES,
            ),
        ]
    };

    FormMapping {
        title: "MODELO 100 — declaración del IRPF (AEAT)",
        header_lines: [
            "Casillas read from Anexo I of Orden HAC/277/2026 (BOE-A-2026-7041, BOE nº 76",
            "of 27-03-2026), the enacted order for ejercicio 2025. Every box below carries",
            "the same number in the ejercicio-2024 order (Orden HAC/242/2025). A form for a",
            "filing year is published in the spring of the next one: for a later year, check",
            "each casilla against that year's own Anexo I before entering it.",
        ]
        .map(str::to_owned)
        .to_vec(),
        boxes,
        footer_lines,
        withholding_casilla: modelo_100::RCM_WITHHOLDING.to_owned(),
    }
}

fn modelo_f93_mapping(statement: &SpanishTaxStatement) -> FormMapping {
    let mut header_lines = vec![
        "Casillas read from the fully numbered form the Boletín Oficial de Navarra".to_owned(),
        format!(
            "publishes as Anexo I of the campaign's Orden Foral: the ejercicio-{}",
            modelo_f93::VERIFIED_EJERCICIO
        ),
        "specimen (Orden Foral 24/2026, BON nº 66 of 07-04-2026, retrieved 2026-08-12).".to_owned(),
    ];

    if statement.year < modelo_f93::VERIFIED_EJERCICIO {
        header_lines.push(format!(
            "WARNING: the ejercicio-{} form has the same structure but its own",
            statement.year
        ));
        header_lines
            .push("numbering was not checked against a specimen. Verify every casilla.".to_owned());
    } else if statement.year > modelo_f93::VERIFIED_EJERCICIO {
        header_lines.push(format!(
            "WARNING: no form is published for ejercicio {} yet — it is filed in {}.",
            statement.year,
            statement.year + 1
        ));
        header_lines.push(format!(
            "These are the ejercicio-{} numbers, the last published layout.",
            modelo_f93::VERIFIED_EJERCICIO
        ));
    }

    let zero = Decimal::ZERO;
    let unconditional = [
        (
            modelo_f93::RCM_DIVIDENDS,
            "Dividendos y participación en beneficios (art. 28.a y b) — importe íntegro (página 2)"
                .to_owned(),
            statement.total_dividend_income,
        ),
        (
            modelo_f93::RCM_INTEREST,
            "Intereses de cuentas y otros rendimientos por cesión de capitales propios (página 2)"
                .to_owned(),
            statement.total_interest_income,
        ),
        (
            modelo_f93::RCM_EXPENSES,
            "Gastos de administración y depósito tras el límite del 3% (art. 32.1.a) (página 2)"
                .to_owned(),
            statement.total_deductible_fees,
        ),
        (
            modelo_f93::RCM_NET,
            "Rendimiento neto del capital mobiliario (página 2)".to_owned(),
            statement.rcm_net,
        ),
        (
            modelo_f93::TRANSFERS_TOTAL,
            "Incremento o disminución de la parte especial del ahorro por transmisiones (anexo 1)"
                .to_owned(),
            statement.gyp_net,
        ),
        (
            modelo_f93::H1_TRANSFERS_POSITIVE,
            "H1 — saldo positivo procedente de transmisiones (anexo 2)".to_owned(),
            std::cmp::max(zero, statement.gyp_net),
        ),
        (
            modelo_f93::H1_OWN_LOSSES,
            "H1 — compensación con saldos negativos propios de transmisiones (anexo 2)".to_owned(),
            statement.gyp_own_group_losses_applied(),
        ),
        (
            modelo_f93::H1_RCM_LOSSES_CROSSED,
            "H1 — compensación con saldos negativos del capital mobiliario (anexo 2)".to_owned(),
            statement.cross_offset_rcm_to_gyp + statement.prior_cross_offset_rcm_to_gyp,
        ),
        (
            modelo_f93::H1_NET,
            "H1 — parte positiva neta procedente de transmisiones (anexo 2)".to_owned(),
            statement.gyp_taxable,
        ),
        (
            modelo_f93::H2_RCM_POSITIVE,
            "H2 — saldo positivo procedente de rendimientos del capital mobiliario (anexo 2)"
                .to_owned(),
            std::cmp::max(zero, statement.rcm_net),
        ),
        (
            modelo_f93::H2_OWN_LOSSES,
            "H2 — compensación con saldos negativos propios del capital mobiliario (anexo 2)"
                .to_owned(),
            statement.rcm_own_group_losses_applied(),
        ),
        (
            modelo_f93::H2_TRANSFER_LOSSES_CROSSED,
            "H2 — compensación con saldos negativos procedentes de transmisiones (anexo 2)"
                .to_owned(),
            statement.cross_offset_gyp_to_rcm + statement.prior_cross_offset_gyp_to_rcm,
        ),
        (
            modelo_f93::H2_NET,
            "H2 — parte positiva neta procedente del capital mobiliario (anexo 2)".to_owned(),
            statement.rcm_taxable,
        ),
        (
            modelo_f93::TOTAL,
            "Total parte especial del ahorro (anexo 2)".to_owned(),
            statement.savings_base,
        ),
        (
            modelo_f93::SAVINGS_BASE,
            "Base liquidable especial del ahorro (anexo 2; repetida en la página 7)".to_owned(),
            statement.savings_base,
        ),
        (
            modelo_f93::SAVINGS_QUOTA,
            "Cuota íntegra especial del ahorro (anexo 2; repetida en la página 7)".to_owned(),
            statement.savings_quota,
        ),
        (
            modelo_f93::FOREIGN_TAX_CREDIT,
            "Deducción por doble imposición internacional (página 6)".to_owned(),
            statement.total_foreign_tax_credit,
        ),
    ];

    // Only carried when they hold something: a zero in a negative-saldo box invites a filer to fill
    // in a block the year does not have.
    let conditional = [
        (
            modelo_f93::TRANSFERS_EXEMPT,
            "Incremento exento — otros supuestos — exención de transmisiones hasta 3.000 € \
             (art. 39.5.d; una celda por transmisión; anexo 1)"
                .to_owned(),
            statement.small_disposals_exemption,
        ),
        (
            modelo_f93::H3_TRANSFERS_NEGATIVE,
            "H3 — saldo negativo procedente de transmisiones — importe en positivo (anexo 2; \
             casilla leída del impreso de 2025)"
                .to_owned(),
            std::cmp::max(zero, -statement.gyp_net),
        ),
        (
            modelo_f93::H4_RCM_NEGATIVE,
            "H4 — saldo negativo procedente de rendimientos del capital mobiliario — importe en \
             positivo (anexo 2)"
                .to_owned(),
            std::cmp::max(zero, -statement.rcm_net),
        ),
        (
            modelo_f93::TRANSFERS_CARRYFORWARD,
            "Saldo negativo de transmisiones a compensar en los ejercicios siguientes (anexo 2; \
             las casillas por año están rotuladas en el impreso)"
                .to_owned(),
            statement.gyp_ledger_next.total(),
        ),
        (
            modelo_f93::RCM_CARRYFORWARD,
            "Saldo negativo del capital mobiliario a compensar en los ejercicios siguientes \
             (anexo 2; las casillas por año están rotuladas en el impreso)"
                .to_owned(),
            statement.rcm_ledger_next.total(),
        ),
    ];

    let boxes = unconditional
        .into_iter()
        .chain(
            conditional
                .into_iter()
                .filter(|(_, _, value)| *value > zero),
        )
        .map(|(casilla, concept, value)| {
            FormBox::new(
                "MODELO_F93_",
                form_name(SpanishTaxRegime::Navarra),
                "",
                casilla,
                &concept,
                value,
            )
        })
        .collect();

    let footer_lines = if statement.gyp_net < zero {
        vec![
            "The year's transmissions are negative, so apartado H3 applies rather than".to_owned(),
            format!(
                "H1: casilla {} above carries the saldo, and the rest of the block —",
                modelo_f93::H3_TRANSFERS_NEGATIVE
            ),
            "the joint-return cells and the per-year carryforward ones — is labelled".to_owned(),
            "on the form itself.".to_owned(),
        ]
    } else {
        Vec::new()
    };

    FormMapping {
        title: "MODELO F-93 — declaración del IRPF de la Comunidad Foral de Navarra",
        header_lines,
        boxes,
        footer_lines,
        withholding_casilla: modelo_f93::RCM_WITHHOLDING.to_owned(),
    }
}

/// How each regime names the six compensation rows.
///
/// The own-group rows carry a real amount under all three regimes, so each names the article that
/// produced it. NF 3/2014 art. 66.1 integrates each group "exclusivamente entre sí" and art. 66.2
/// requires absorbing the maximum each year; TRLFIRPF art. 54.2 letra a) is the capital-mobiliario
/// group and letra b) the transmisiones one, each absorbing its own prior saldos only when its own
/// result is positive. Neither is the AEAT "fase" numbering, which is Territorio Común's own scheme.
///
/// The cross rows are structurally zero under Gipuzkoa — art. 66.1 never lets a saldo leave its own
/// group — so it keeps the state wording rather than earning a vocabulary for a row that cannot
/// fire. Under Navarra a negative in either letra crosses at 25% of the other's positive *after*
/// that other absorbed its own carryforwards.
pub(super) struct CompensationLabels {
    pub own_rcm: &'static str,
    pub own_gyp: &'static str,
    pub cross_rcm: &'static str,
    pub cross_gyp: &'static str,
    pub prior_rcm: &'static str,
    pub prior_gyp: &'static str,
}

pub(super) fn compensation_labels(regime: SpanishTaxRegime) -> CompensationLabels {
    let (own_rcm, own_gyp) = match regime {
        SpanishTaxRegime::Comun => (
            "Saldos negativos de ejercicios anteriores aplicados al propio grupo (RCM) — fase 2ª-1º",
            "Saldos negativos de ejercicios anteriores aplicados al propio grupo (ganancias) — fase 2ª-1º",
        ),
        SpanishTaxRegime::Gipuzkoa => (
            "Saldos negativos de ejercicios anteriores aplicados al propio grupo (RCM) — NF \
             3/2014 art. 66.1.a: los rendimientos se integran y compensan exclusivamente entre \
             sí y en la cuantía máxima que permita cada ejercicio (art. 66.2) — sólo Gipuzkoa",
            "Saldos negativos de ejercicios anteriores aplicados al propio grupo (ganancias) — \
             NF 3/2014 art. 66.1.b: las ganancias y pérdidas se integran y compensan \
             exclusivamente entre sí y en la cuantía máxima que permita cada ejercicio (art. \
             66.2) — sólo Gipuzkoa",
        ),
        SpanishTaxRegime::Navarra => (
            "Saldos negativos de ejercicios anteriores aplicados al propio grupo (RCM) — art. \
             54.2.a: sólo si el resultado del ejercicio es positivo y con el límite de cero — \
             sólo Navarra",
            "Saldos negativos de ejercicios anteriores aplicados al propio grupo (ganancias) — \
             art. 54.2.b: sólo si el resultado del ejercicio es positivo y con el límite de \
             cero — sólo Navarra",
        ),
    };

    let (cross_rcm, cross_gyp, prior_rcm, prior_gyp) = match regime {
        SpanishTaxRegime::Gipuzkoa | SpanishTaxRegime::Comun => (
            "Compensación cruzada RCM → ganancias — fase 1ª (25% — sólo Territorio Común)",
            "Compensación cruzada ganancias → RCM — fase 1ª (25% — sólo Territorio Común)",
            "Compensación cruzada RCM → ganancias — fase 2ª-2º (saldos de ejercicios anteriores)",
            "Compensación cruzada ganancias → RCM — fase 2ª-2º (saldos de ejercicios anteriores)",
        ),
        SpanishTaxRegime::Navarra => (
            "Compensación cruzada RCM → ganancias — art. 54.2.a: 25% del saldo positivo \
             resultante de la letra b) — sólo Navarra",
            "Compensación cruzada ganancias → RCM — art. 54.2.b: 25% del saldo positivo \
             resultante de la letra a) — sólo Navarra",
            "Compensación cruzada RCM → ganancias — art. 54.2.a en el mismo orden (saldos de \
             ejercicios anteriores)",
            "Compensación cruzada ganancias → RCM — art. 54.2.b en el mismo orden (saldos de \
             ejercicios anteriores)",
        ),
    };

    CompensationLabels {
        own_rcm,
        own_gyp,
        cross_rcm,
        cross_gyp,
        prior_rcm,
        prior_gyp,
    }
}

/// How each regime names the foreign-currency result row.
///
/// Navarra is the only regime with a €3,000 exemption for the conversions to be measured against,
/// so it is the only one whose FX row has a scope limit to declare. The limit holds every year,
/// including the ones where no relief was withheld, so it belongs on the row the file always
/// carries rather than on a banner that fires in some years only.
pub(super) fn fx_summary_label(regime: SpanishTaxRegime) -> &'static str {
    match regime {
        SpanishTaxRegime::Gipuzkoa | SpanishTaxRegime::Comun => {
            "Ganancias y pérdidas por conversión de divisa"
        }
        SpanishTaxRegime::Navarra => {
            "Ganancias y pérdidas por conversión de divisa (TRLFIRPF art. 54.1.b) — se \
             gravan íntegras: no se les aplica la exención del art. 39.5.d ni cuentan para \
             su importe global (registro §13 de docs/spain-taxes.md)"
        }
    }
}

#[cfg(test)]
mod tests {
    use crate::taxes::spain::carryforward::LossLedger;
    use crate::taxes::spain::compensation::CrossOffset;
    use crate::taxes::spain::scale::SavingsScale;
    use crate::types::Date;

    use super::*;

    fn statement(regime: SpanishTaxRegime, year: i32) -> SpanishTaxStatement {
        SpanishTaxStatement::new(
            year,
            regime,
            SavingsScale::for_year(regime, year).unwrap(),
            LossLedger::default(),
            LossLedger::default(),
            CrossOffset::None,
            dec!(0.15),
            Decimal::ZERO,
            None,
            false,
        )
    }

    /// Every corpus case files 2026, so no golden pins the Anexo 3 branch: it exists for ejercicios
    /// up to 2024 only. Without this test the two casillas could be renumbered or dropped and the
    /// whole suite would stay green.
    #[test]
    fn a_2024_gipuzkoa_return_carries_the_anexo_3_breakdown() {
        let mut spain = statement(SpanishTaxRegime::Gipuzkoa, 2024);
        spain.calculate_totals();

        let mapping = form_mapping(&spain);
        let keys: Vec<&str> = mapping.boxes.iter().map(|form| form.key.as_str()).collect();

        assert!(keys.contains(&"MODELO_109_ANEXO3_06+16"));
        assert!(keys.contains(&"MODELO_109_ANEXO3_17"));
        assert!(keys.contains(&"MODELO_109_HOJA_60"));
        assert!(keys.contains(&"MODELO_109_HOJA_64"));

        // The Anexo 3 rows lead, and each names its own sheet: Hoja 28 and Anexo 4's own 28 are
        // different casillas, so a label without the sheet would send a filer to the wrong one.
        assert_eq!(keys[0], "MODELO_109_ANEXO3_06+16");
        assert_eq!(
            mapping.boxes[0].label(),
            "Rendimientos íntegros del capital mobiliario (excluida la renta exenta) \
             (anexo 3, casilla 06+16)"
        );
    }

    /// NF 1/2025 renumbered the deduction block, and the Anexo 3 breakdown goes with it.
    #[test]
    fn a_2025_gipuzkoa_return_renumbers_the_deduction_and_drops_anexo_3() {
        let mut spain = statement(SpanishTaxRegime::Gipuzkoa, 2025);
        spain.calculate_totals();

        let mapping = form_mapping(&spain);
        let keys: Vec<&str> = mapping.boxes.iter().map(|form| form.key.as_str()).collect();

        assert!(keys.contains(&"MODELO_109_HOJA_70"));
        assert!(keys.contains(&"MODELO_109_HOJA_74"));
        assert!(!keys.iter().any(|key| key.contains("ANEXO3")));
        assert!(
            mapping
                .header_lines
                .iter()
                .any(|line| line.contains("renumbered by NF 1/2025")),
            "{:#?}",
            mapping.header_lines
        );
    }

    /// A form with one numbering space labels its rows with the concept alone.
    ///
    /// The label also has to name 0460 for what the AEAT calls it. LIRPF art. 50 makes the base
    /// *liquidable* del ahorro casilla 0510 — 0460 minus whatever is left of the reducciones por
    /// tributación conjunta, pensiones compensatorias y anualidades por alimentos. The tool models
    /// none of those, so its figure is the *imponible*; calling it liquidable would send a filer
    /// to a box one step further down the form.
    #[test]
    fn the_comun_savings_base_is_the_imponible_and_carries_no_sheet() {
        let mut spain = statement(SpanishTaxRegime::Comun, 2026);
        spain.calculate_totals();

        let mapping = form_mapping(&spain);
        let savings_base = mapping
            .boxes
            .iter()
            .find(|form| form.casilla == "0460")
            .unwrap();
        assert_eq!(savings_base.form, "Modelo 100");
        assert_eq!(savings_base.sheet, "");
        assert!(
            savings_base
                .label()
                .starts_with("Base imponible del ahorro")
        );
        assert!(savings_base.label().contains("0510"));
        assert!(!mapping.boxes.iter().any(|form| form.casilla == "0510"));
    }

    fn fx_entry(amount_eur: Decimal) -> crate::tax_statement::spain::statement::FxGainEntry {
        crate::tax_statement::spain::statement::FxGainEntry {
            date: Date::from_ymd_opt(2026, 3, 1).unwrap(),
            currency: "USD".to_owned(),
            acquisition_date: Date::from_ymd_opt(2026, 1, 1).unwrap(),
            amount_eur,
            activity_code: "FOREX".to_owned(),
        }
    }

    /// The ganancias group as the Modelo 100 block reports it: the acciones-cotizadas figure plus
    /// the otros-elementos sums, which are absent when the year had no conversion.
    ///
    /// The three are one figure split three ways, so this must equal `gyp_net` however the year is
    /// shaped. A broken split shows up here as casillas that no longer add back up to the group the
    /// rest of the report reports.
    fn ganancias_across_the_boxes(mapping: &FormMapping) -> Decimal {
        let box_of = |casilla: &str| {
            mapping
                .boxes
                .iter()
                .find(|form| form.casilla == casilla)
                .map_or(Decimal::ZERO, |form| form.value)
        };
        box_of(modelo_100::LISTED_CAPITAL_GAINS) + box_of(modelo_100::OTHER_ELEMENTS_GAINS)
            - box_of(modelo_100::OTHER_ELEMENTS_LOSSES)
    }

    /// The 0326-0340 block is the acciones-cotizadas one; a currency conversion transmits a
    /// different kind of element. The result leaves that block and lands in the otros-elementos
    /// sums of apartado F2, so the filer never posts a share figure that silently contains one.
    #[test]
    fn a_comun_year_puts_currency_results_in_the_otros_elementos_sums() {
        let mut spain = statement(SpanishTaxRegime::Comun, 2026);
        spain.calculate_totals();
        let mapping = form_mapping(&spain);
        assert!(mapping.footer_lines.is_empty());
        // A year without a conversion says nothing about the block.
        for casilla in [
            modelo_100::OTHER_ELEMENTS_GAINS,
            modelo_100::OTHER_ELEMENTS_LOSSES,
        ] {
            assert!(!mapping.boxes.iter().any(|form| form.casilla == casilla));
        }
        // With no conversion the shares block carries the whole group: nothing is subtracted from
        // it and no otros-elementos box stands in for the part that was taken out.
        assert_eq!(ganancias_across_the_boxes(&mapping), spain.gyp_net);

        // One conversion up €400 and one down €150: the form keeps the two sides apart, so the net
        // is never what gets posted.
        spain.fx_gains.push(fx_entry(dec!(400)));
        spain.fx_gains.push(fx_entry(dec!(-150)));
        spain.calculate_totals();

        let mapping = form_mapping(&spain);
        let box_of = |casilla: &str| {
            mapping
                .boxes
                .iter()
                .find(|form| form.casilla == casilla)
                .unwrap_or_else(|| panic!("casilla {casilla} missing"))
                .value
        };
        assert_eq!(box_of(modelo_100::OTHER_ELEMENTS_GAINS), dec!(400));
        assert_eq!(box_of(modelo_100::OTHER_ELEMENTS_LOSSES), dec!(150));
        // The shares block keeps only what the shares did: gyp_net is €250 of currency here.
        assert_eq!(spain.total_fx_result, dec!(250));
        assert_eq!(
            box_of(modelo_100::LISTED_CAPITAL_GAINS),
            spain.gyp_net - dec!(250)
        );

        assert_eq!(ganancias_across_the_boxes(&mapping), spain.gyp_net);

        let footer = mapping.footer_lines.join(" ");
        assert!(footer.contains("apartado F2"), "{footer}");
        assert!(footer.contains(modelo_100::OTHER_ELEMENTS), "{footer}");
        // Clave 4, not 5: 5 is the afectos one and would route the gain into casilla 0387.
        assert!(
            footer.contains(&format!(
                "clave {} =",
                modelo_100::OTHER_ELEMENTS_PRIVATE_KEY
            )),
            "{footer}"
        );
        assert!(!footer.contains("clave 5"), "{footer}");
        // The per-element boxes the filer still has to fill in row by row.
        for casilla in [
            modelo_100::OTHER_ELEMENTS_KIND,
            modelo_100::OTHER_ELEMENTS_DISPOSAL_VALUE,
            modelo_100::OTHER_ELEMENTS_ACQUISITION_VALUE,
            modelo_100::OTHER_ELEMENTS_LOSS_IMPUTABLE,
            modelo_100::OTHER_ELEMENTS_GAIN_IMPUTABLE,
        ] {
            assert!(footer.contains(casilla), "{casilla} missing from {footer}");
        }
    }

    /// The header must not go on calling an enacted order a draft.
    #[test]
    fn the_modelo_100_header_cites_the_enacted_order() {
        let mut spain = statement(SpanishTaxRegime::Comun, 2026);
        spain.calculate_totals();

        let header = form_mapping(&spain).header_lines.join(" ");
        assert!(header.contains("BOE-A-2026-7041"), "{header}");
        assert!(header.contains("Orden HAC/277/2026"), "{header}");
        assert!(!header.to_lowercase().contains("draft"), "{header}");
    }
}
